export const sstSurveyPO = { 

    //Login Page Elements
    pivotLogo: 'img',
    sstLabel:'.fzaoYV',
    sstSubLabel:'.fwlSGW',
    sstTalkLabel:'[class="sc-mfv47r-0 hLgsZj"]',
    surveyID:'#survey-id',
    studentID:'#student-id',
    sstLoginBtn:'.MuiButton-label',

    //Onboarding Elements
    greetings:'#onboarding-greetings',
    feedbackSubtext:'.kATjNo',
    subtext:'.dyckeG',
    sliderRightArrow:'[data-testid="onboarding-slider-right-arrow"] > .sc-15fa221-0 > img',
    sliderRightArrow2:'[data-testid="onboarding-slider-right-arrow"] > .sc-15fa221-0 > img',
    imgSlides:'.slick-active > :nth-child(1) > div > img',
    startSurveyBtn:'[data-testid="start-survey-button"]',
    
    //SST Survey Elements
    studentName:'.ewzZu',
    sst_question_1:'#sst-question-1',
    sst_question_2:'#sst-question-2',
    sst_question_3:'#sst-question-3',
    sst_question_4:'#sst-question-4',
    sst_question_5:'#sst-question-5',
    sst_question_6:'#sst-question-6',
    sst_question_7:'#sst-question-7',
    sst_question_8:'#sst-question-8',
    sst_question_9:'#sst-question-9',
    sst_question_10:'#sst-question-10',
    sst_question_11:'#sst-question-11',
    sst_question_12:'#sst-question-12',
    sst_question_13:'#sst-question-13',
    sst_question_14:'#sst-question-14',
    sst_question_15:'#sst-question-15',
    sst_question_16:'#sst-question-16',
    sst_question_17:'#sst-question-17',
    sst_question_18:'#sst-question-18',
    sst_question_19:'#sst-question-19',
    sst_question_20:'#sst-question-20',
    sst_question_21:'#sst-question-21',
    sst_question_22:'#sst-question-22',
    sst_question_23:'#sst-question-23',
    sst_question_24:'#sst-question-24',
    sst_question_25:'#sst-question-25',
    radio_q1_response:'#sst-question-1-response',
    radio_q2_response:'#sst-question-2-response',
    radio_q3_response:'#sst-question-3-response',
    radio_q4_response:'#sst-question-4-response',
    radio_q5_response:'#sst-question-5-response',
    radio_q6_response:'#sst-question-6-response',
    radio_q7_response:'#sst-question-7-response',
    radio_q8_response:'#sst-question-8-response',
    radio_q9_response:'#sst-question-9-response',
    radio_q10_response:'#sst-question-10-response',
    radio_q11_response:'#sst-question-11-response',
    radio_q12_response:'#sst-question-12-response',
    radio_q13_response:'#sst-question-13-response',
    radio_q14_response:'#sst-question-14-response',
    radio_q15_response:'#sst-question-15-response',
    radio_q16_response:'#sst-question-16-response',
    radio_q17_response:'#sst-question-17-response',
    radio_q18_response:'#sst-question-18-response',
    radio_q19_response:'#sst-question-19-response',
    radio_q20_response:'#sst-question-20-response',
    radio_q21_response:'#sst-question-21-response',
    radio_q22_response:'#sst-question-22-response',
    radio_q23_response:'#sst-question-23-response',
    radio_q24_response:'#sst-question-24-response',
    radio_q25_response:'#sst-question-25-response',
    submitBtn:'#submit-button',

    student_name:'#student-name',
    level1_sst_question1:'#sst-question-0',
    level1_sst_response1:'#sst-question-0-response',
    level1_sst_question2:'#sst-question-1',
    level1_sst_response2:'#sst-question-1-response',
    level1_sst_question3:'#sst-question-2',
    level1_sst_response3:'#sst-question-2-response',
    level1_sst_question4:'#sst-question-3',
    level1_sst_response4:'#sst-question-3-response',
    level1_sst_question5:'#sst-question-4',
    level1_sst_response5:'#sst-question-4-response',
    level1_sst_question6:'#sst-question-5',
    level1_sst_response6:'#sst-question-5-response',
    level1_sst_question7:'#sst-question-6',
    level1_sst_response7:'#sst-question-6-response',
    level1_sst_question8:'#sst-question-7',
    level1_sst_response8:'#sst-question-7-response',
    level1_sst_question9:'#sst-question-8',
    level1_sst_response9:'#sst-question-8-response',
    nextBtn:'#sst-question-next-button',
    childNextBtn:'.sc-mfv47r-0',
    goBackBtn:'#sst-question-back-button',
    submitSurvey:'#sst-question-submit-button',
    audioBtn:'#sst-question-0-audio-button',
    modal_Logout:'#logout-confirm',
    modal_ResumeSurvey:'#logout-cancel',
    

    //Thank You Page Elements
    thankyouTitle:'#thank-you-title', //You are finished!
    thankyouSubtitle:'#thank-you-subtitle', //Thank you for your feedback.
    thankyouIcon:'#thank-you-image',
    thankyouFooter:'#thank-you-footer',
    thankyouLogout:'#logout-button',
    logoutBtn:'.sc-1tfore2-5'
}